In [1]:
import numpy as np
import pandas as pd

In [2]:
interferon_genes_df=pd.read_csv('./RNA_DATA/Type_l_Interferon_gene_sets_all(MsigDB)_v3.csv')

In [3]:
interferon_genes_df

,DER_IFN_ALPHA_RESPONSE_DN,DER_IFN_ALPHA_RESPONSE_UP,DER_IFN_BETA_RESPONSE_DN,DER_IFN_BETA_RESPONSE_UP,GOBP_NEGATIVE_REGULATION_OF_TYPE_I_INTERFERON_PRODUCTION,GOBP_POSITIVE_REGULATION_OF_TYPE_I_INTERFERON_PRODUCTION,GOBP_RESPONSE_TO_TYPE_I_INTERFERON,GOBP_TYPE_I_INTERFERON_PRODUCTION,ISHIKAWA_STING_SIGNALING,KEGG_CYTOSOLIC_DNA_SENSING_PATHWAY,KEGG_MEDICUS_REFERENCE_TYPE_I_INTERFERON_TO_JAK_STAT_SIGNALING_PATHWAY,KEGG_RIG_I_LIKE_RECEPTOR_SIGNALING_PATHWAY,WP_INTERFERON_TYPE_I_SIGNALING,WP_TYPE_I_INTERFERON_INDUCTION_AND_SIGNALING_DURING_SARSCOV2_INFECTION
0,COX17,ADAR,ARHGAP4,ADAM9,ACOD1,ARRDC4,ADAR,ACOD1,ADAR,ADAR,IFNA1,ATG12,CBL,ACE2
1,EIF3E,ATP6V0B,CHRNB2,ADAR,ATG12,CD14,AZI2,ARRDC4,CCL5,AIM2,IFNA10,ATG5,CREB1,EIF2AK2
2,FBXW4P1,B2M,IGF2,AP3M2,ATG5,CGAS,CACTIN,ATG12,IFNA1,CASP1,IFNA13,AZI2,CRK,IFIH1
3,FEZ1,BAG1,PLPP3,ARID3A,ATG9A,CHUK,CDC37,ATG5,IFNB1,CCL4,IFNA14,CASP10,CRKL,IFNAR1
4,LARP4B,BBC3,SGSH,ATP6V0B,BANF1,CLEC12A,CH25H,ATG9A,IRF1,CCL4L2,IFNA16,CASP8,EIF4A1,IFNAR2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XIAP,NaN,NaN,NaN,NaN,NaN,NaN
127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YY1,NaN,NaN,NaN,NaN,NaN,NaN
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZBTB20,NaN,NaN,NaN,NaN,NaN,NaN
129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZC3HAV1,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZCCHC3,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
interferon_genes = interferon_genes_df.stack().unique() #stack()把每一欄變成一個series(自動去NA) #unique()取不重複 ->重複的gene只保留一次

interferon_genes_list = list(interferon_genes)

interferon_df = pd.DataFrame({'Type I Interferon genes':interferon_genes_list})

print(f"總共 {len(interferon_genes)} 個不重複的Type I Interferon genes")

總共 400 個不重複的Type I Interferon genes

In [5]:
interferon_df

    Type I Interferon genes
0                     COX17
1                      ADAR
2                   ARHGAP4
3                     ADAM9
4                     ACOD1
..                      ...
395                   RNF26
396                   TEAD1
397                TRAPPC10
398                   TIRAP
399                  TRIM38

[400 rows x 1 columns]

In [6]:
#interferon_df.to_csv('./RNA_DATA/Type I Interferon gene list(MsigDB).csv',index=False,header=True)

In [7]:
reference_interferon_genes = [
    "IL1RN", "IFIT5", "IFIT3", "IFIT2", "IFI6", "HERC5",
    "CMPK2", "IFIT1", "MX1", "ISG15", "OASL", "RSAD2",
    "IFI44L", "OAS3", "IFI44", "XAF1", "EIF2AK2", "LAP3",
    "LY6E", "OAS2", "OAS1", "USP18", "HERC6", "SIGLEC1",
    "IFI27"
]

In [8]:
len(reference_interferon_genes)

25

In [9]:
Type_I_IFN_set = set(interferon_genes_list)

present   = [g for g in reference_interferon_genes if g in Type_I_IFN_set]
missing   = [g for g in reference_interferon_genes if g not in Type_I_IFN_set]

print("在 Type I IFN 中：", present)
print("不在 Type I IFN 中：", missing)

在 Type I IFN 中： ['IFIT5', 'IFIT3', 'IFIT2', 'IFI6', 'IFIT1', 'MX1', 'ISG15', 'OASL', 'OAS3', 'IFI44', 'XAF1', 'EIF2AK2', 'OAS2', 'OAS1', 'USP18', 'SIGLEC1', 'IFI27']
不在 Type I IFN 中： ['IL1RN', 'HERC5', 'CMPK2', 'RSAD2', 'IFI44L', 'LAP3', 'LY6E', 'HERC6']