In [2]:
import numpy as np
import pandas as pd

In [6]:
interferon_genes_df=pd.read_csv('./RNA_DATA/Type_l_Interferon_gene_sets_all(MsigDB)_v2_2.csv')

In [7]:
interferon_genes_df

,DER_IFN_ALPHA_RESPONSE_DN,DER_IFN_ALPHA_RESPONSE_UP,DER_IFN_BETA_RESPONSE_DN,DER_IFN_BETA_RESPONSE_UP,GOBP_NEGATIVE_REGULATION_OF_TYPE_I_INTERFERON_PRODUCTION,GOBP_POSITIVE_REGULATION_OF_TYPE_I_INTERFERON_PRODUCTION,GOBP_RESPONSE_TO_TYPE_I_INTERFERON,GOBP_TYPE_I_INTERFERON_PRODUCTION,GSE16450_CTRL_VS_IFNA_12H_STIM_IMMATURE_NEURON_CELL_LINE_DN,GSE16450_CTRL_VS_IFNA_12H_STIM_IMMATURE_NEURON_CELL_LINE_UP,...,GSE5542_UNTREATED_VS_IFNA_TREATED_EPITHELIAL_CELLS_24H_DN,GSE5542_UNTREATED_VS_IFNA_TREATED_EPITHELIAL_CELLS_24H_UP,GSE5542_UNTREATED_VS_IFNA_TREATED_EPITHELIAL_CELLS_6H_DN,GSE5542_UNTREATED_VS_IFNA_TREATED_EPITHELIAL_CELLS_6H_UP,ISHIKAWA_STING_SIGNALING,KEGG_CYTOSOLIC_DNA_SENSING_PATHWAY,KEGG_MEDICUS_REFERENCE_TYPE_I_INTERFERON_TO_JAK_STAT_SIGNALING_PATHWAY,KEGG_RIG_I_LIKE_RECEPTOR_SIGNALING_PATHWAY,WP_INTERFERON_TYPE_I_SIGNALING,WP_TYPE_I_INTERFERON_INDUCTION_AND_SIGNALING_DURING_SARSCOV2_INFECTION
0,COX17,ADAR,ARHGAP4,ADAM9,ACOD1,ARRDC4,ADAR,ACOD1,ADAMTS19,ABL2,...,ABRAXAS1,ABR,AASDH,ACOT9,ADAR,ADAR,IFNA1,ATG12,CBL,ACE2
1,EIF3E,ATP6V0B,CHRNB2,ADAR,ATG12,CD14,AZI2,ARRDC4,ADGRE2,ABTB3,...,ACBD4,ACADVL,ACKR3,ACTN4,CCL5,AIM2,IFNA10,ATG5,CREB1,EIF2AK2
2,FBXW4P1,B2M,IGF2,AP3M2,ATG5,CGAS,CACTIN,ATG12,ADGRG3,ACACA,...,ACKR3,ACOT9,ACTN1,ADK,IFNA1,CASP1,IFNA13,AZI2,CRK,IFIH1
3,FEZ1,BAG1,PLPP3,ARID3A,ATG9A,CHUK,CDC37,ATG5,ADM,ADGRA3,...,ADPRM,ADAM8,ADGRE4P,AHNAK,IFNB1,CCL4,IFNA14,CASP10,CRKL,IFNAR1
4,LARP4B,BBC3,SGSH,ATP6V0B,BANF1,CLEC12A,CH25H,ATG9A,AEN,ADK,...,AFF2,ADCY9,AK2,ALCAM,IRF1,CCL4L2,IFNA16,CASP8,EIF4A1,IFNAR2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZNF689,...,ZNF780B,YWHAH,ZNF84,UST,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZNF839,...,ZNF84,ZDHHC7,ZNF91,ZBTB49,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ZNF335,ZP3,ZC3H12C,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ZNF532,NaN,ZEB2,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ZNF821,NaN,ZFYVE1,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
interferon_genes = interferon_genes_df.stack().unique() #stack()把每一欄變成一個series(自動去NA) #unique()取不重複 ->重複的gene只保留一次

interferon_genes_list = list(interferon_genes)

interferon_df = pd.DataFrame({'Type I Interferon genes':interferon_genes_list})

print(f"總共 {len(interferon_genes)} 個不重複的Type I Interferon genes")

總共 7935 個不重複的Type I Interferon genes

In [10]:
interferon_df

     Type I Interferon genes
0                      COX17
1                       ADAR
2                    ARHGAP4
3                      ADAM9
4                      ACOD1
...                      ...
7930                  ZNF296
7931                 ZNF280D
7932                  ZNF474
7933                  ZNF821
7934                  ZFYVE1

[7935 rows x 1 columns]

In [13]:
hallmark_IFN_df=pd.read_csv('./RNA_DATA/MsigDB_collection/hallmark_IFN-I.csv')
hallmark_IFN_df=hallmark_IFN_df.iloc[1:,]

In [14]:
hallmark_IFN_df

   HALLMARK_INTERFERON_ALPHA_RESPONSE
1                                ADAR
2                                 B2M
3                               BATF2
4                                BST2
5                                 C1S
..                                ...
93                              TXNIP
94                               UBA7
95                             UBE2L6
96                              USP18
97                              WARS1

[97 rows x 1 columns]

In [20]:
overlap_count=hallmark_IFN_df['HALLMARK_INTERFERON_ALPHA_RESPONSE'].isin(interferon_df ['Type I Interferon genes']).sum()
print(f'Overlap gene counts:',overlap_count)

Overlap gene counts: 86

In [14]:
#interferon_df.to_csv('./RNA_DATA/Type I Interferon gene list(MsigDB).csv',index=False,header=True)

In [21]:
reference_interferon_genes = [
    "IL1RN", "IFIT5", "IFIT3", "IFIT2", "IFI6", "HERC5",
    "CMPK2", "IFIT1", "MX1", "ISG15", "OASL", "RSAD2",
    "IFI44L", "OAS3", "IFI44", "XAF1", "EIF2AK2", "LAP3",
    "LY6E", "OAS2", "OAS1", "USP18", "HERC6", "SIGLEC1",
    "IFI27"
]

In [22]:
len(reference_interferon_genes)

25

In [25]:
Type_I_IFN_set = set(interferon_genes_list)

present   = [g for g in reference_interferon_genes if g in Type_I_IFN_set]
missing   = [g for g in reference_interferon_genes if g not in Type_I_IFN_set]

print("在 Type I IFN 中：", present)
print("不在 Type I IFN 中：", missing)

在 Type I IFN 中： ['IL1RN', 'IFIT5', 'IFIT3', 'IFIT2', 'IFI6', 'HERC5', 'CMPK2', 'IFIT1', 'MX1', 'ISG15', 'OASL', 'RSAD2', 'IFI44L', 'OAS3', 'IFI44', 'XAF1', 'EIF2AK2', 'LAP3', 'LY6E', 'OAS2', 'OAS1', 'USP18', 'HERC6', 'SIGLEC1', 'IFI27']
不在 Type I IFN 中： []

In [32]:
hallmark_Type_I_IFN_set = set(hallmark_IFN_df['HALLMARK_INTERFERON_ALPHA_RESPONSE'])

present   = [g for g in reference_interferon_genes if g in hallmark_Type_I_IFN_set]
missing   = [g for g in reference_interferon_genes if g not in hallmark_Type_I_IFN_set]

print("在 Type I IFN 中：", present)
print("不在 Type I IFN 中：", missing)

在 Type I IFN 中： ['IFIT3', 'IFIT2', 'CMPK2', 'MX1', 'ISG15', 'OASL', 'RSAD2', 'IFI44L', 'IFI44', 'EIF2AK2', 'LAP3', 'LY6E', 'OAS1', 'USP18', 'HERC6', 'IFI27']
不在 Type I IFN 中： ['IL1RN', 'IFIT5', 'IFI6', 'HERC5', 'IFIT1', 'OAS3', 'XAF1', 'OAS2', 'SIGLEC1']

### **Each Collection I-IFN gene counts**

In [15]:
import numpy as np
import pandas as pd
import os
folder_path = "./RNA_DATA/MsigDB_collection"
numbers={}
for file_name in os.listdir(folder_path):
    if file_name.endswith(".csv"):
        file_path = os.path.join(folder_path, file_name)
        print(f"讀取: {file_path}")
    interferon_genes_df=pd.read_csv(file_path)
    interferon_genes_df=interferon_genes_df.iloc[1:,]
    interferon_genes = interferon_genes_df.stack().unique() #stack()把每一欄變成一個series(自動去NA) #unique()取不重複 ->重複的gene只保留一次
    numbers[file_name] = len(interferon_genes)

# 轉成 DataFrame
interferon_df = pd.DataFrame.from_dict(numbers, orient='index', columns=["Gene_count"])
print(interferon_df)

讀取: ./RNA_DATA/MsigDB_collection\CGP.csv
讀取: ./RNA_DATA/MsigDB_collection\CP.csv
讀取: ./RNA_DATA/MsigDB_collection\GO.csv
讀取: ./RNA_DATA/MsigDB_collection\ImmuneSigDB.csv
                 Gene_count
CGP.csv                 128
CP.csv                  163
GO.csv                  199
ImmuneSigDB.csv        7759